
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vira Meliana
 */
public class frametoko extends javax.swing.JFrame {
String nol_jam ="";
String nol_menit = "";
String nol_detik = "";
    /**
     * Creates new form frametoko
     */
    public frametoko() {
        initComponents();
        setTanggal();
        setJam();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nmksr = new javax.swing.JTextField();
        idbrg = new javax.swing.JTextField();
        nmbrg1 = new javax.swing.JTextField();
        jmlbrg = new javax.swing.JTextField();
        txtdiskon = new javax.swing.JTextField();
        tanggal = new com.toedter.calendar.JDateChooser();
        refresh = new javax.swing.JButton();
        btndiskon = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        labeljam = new javax.swing.JLabel();
        labeltanggal = new javax.swing.JLabel();
        btnprint = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        hrgbrg2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Tanggal");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 370, 130, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Id Barang");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 120, 130, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Nama Barang");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 170, 130, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Jumlah Barang");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 420, 130, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Diskon");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 270, 130, 40);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Nama Kasir");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 320, 130, 40);

        nmksr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmksrActionPerformed(evt);
            }
        });
        getContentPane().add(nmksr);
        nmksr.setBounds(140, 320, 170, 40);

        idbrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idbrgActionPerformed(evt);
            }
        });
        getContentPane().add(idbrg);
        idbrg.setBounds(140, 120, 170, 40);

        nmbrg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmbrg1ActionPerformed(evt);
            }
        });
        getContentPane().add(nmbrg1);
        nmbrg1.setBounds(140, 170, 170, 40);

        jmlbrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlbrgActionPerformed(evt);
            }
        });
        getContentPane().add(jmlbrg);
        jmlbrg.setBounds(140, 420, 170, 40);

        txtdiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdiskonActionPerformed(evt);
            }
        });
        getContentPane().add(txtdiskon);
        txtdiskon.setBounds(140, 270, 170, 40);
        getContentPane().add(tanggal);
        tanggal.setBounds(140, 370, 180, 40);

        refresh.setBackground(new java.awt.Color(255, 51, 0));
        refresh.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        getContentPane().add(refresh);
        refresh.setBounds(890, 120, 80, 40);

        btndiskon.setBackground(new java.awt.Color(255, 51, 0));
        btndiskon.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btndiskon.setText("diskon");
        btndiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndiskonActionPerformed(evt);
            }
        });
        getContentPane().add(btndiskon);
        btndiskon.setBounds(340, 270, 80, 40);

        btnsave.setBackground(new java.awt.Color(255, 51, 0));
        btnsave.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnsave);
        btnsave.setBounds(530, 120, 80, 40);

        btndelete.setBackground(new java.awt.Color(255, 51, 0));
        btndelete.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete);
        btndelete.setBounds(620, 120, 80, 40);

        btnclear.setBackground(new java.awt.Color(255, 51, 0));
        btnclear.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear);
        btnclear.setBounds(710, 120, 80, 40);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "idbarang", "namabarang", "hargabarang", "tanggal", "namakasir", "jumlahbarang", "totalharga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(3).setResizable(false);
            table.getColumnModel().getColumn(4).setResizable(false);
            table.getColumnModel().getColumn(5).setResizable(false);
            table.getColumnModel().getColumn(6).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(452, 200, 540, 240);

        jButton6.setText("Save");
        getContentPane().add(jButton6);
        jButton6.setBounds(530, 120, 80, 40);

        labeljam.setText("Jam");
        getContentPane().add(labeljam);
        labeljam.setBounds(580, 60, 110, 20);

        labeltanggal.setText("Tanggal");
        getContentPane().add(labeltanggal);
        labeltanggal.setBounds(580, 20, 150, 30);

        btnprint.setBackground(new java.awt.Color(255, 51, 0));
        btnprint.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnprint.setText("Print");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });
        getContentPane().add(btnprint);
        btnprint.setBounds(800, 120, 80, 40);

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Transaksi");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 10, 130, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1020, 100);

        hrgbrg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrgbrg2ActionPerformed(evt);
            }
        });
        getContentPane().add(hrgbrg2);
        hrgbrg2.setBounds(140, 220, 170, 40);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Harga Barang");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 220, 130, 40);

        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        getContentPane().add(total);
        total.setBounds(140, 470, 170, 40);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Total Harga");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 470, 130, 40);

        jButton1.setBackground(new java.awt.Color(255, 51, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("total");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(340, 470, 80, 40);

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));
        jPanel2.setLayout(null);
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 100, 430, 420);

        jPanel3.setBackground(new java.awt.Color(255, 204, 51));
        jPanel3.setLayout(null);
        getContentPane().add(jPanel3);
        jPanel3.setBounds(430, 100, 590, 70);

        jPanel4.setBackground(new java.awt.Color(255, 204, 102));
        jPanel4.setLayout(null);
        getContentPane().add(jPanel4);
        jPanel4.setBounds(430, 170, 590, 350);

        setBounds(0, 0, 1035, 562);
    }// </editor-fold>//GEN-END:initComponents

    private void nmksrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmksrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmksrActionPerformed

    private void idbrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idbrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idbrgActionPerformed

    private void nmbrg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmbrg1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmbrg1ActionPerformed

    private void jmlbrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlbrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlbrgActionPerformed

    private void txtdiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdiskonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdiskonActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
selectData();

        // TODO add your handling code here:
    }//GEN-LAST:event_refreshActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed

           SimpleDateFormat dateFormat = new SimpleDateFormat("yyy-MM-dd");
       String tgl = dateFormat.format(tanggal.getDate());
        if ("".equals(idbrg.getText()) || "".equals(nmbrg1.getText()) || "".equals(jmlbrg.getText()) || "".equals(nmksr.getText())|| "".equals(hrgbrg2.getText()))
                {JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
                
                }
     
        String SQL = "INSERT INTO tb_admin VALUES "
                + "('"+idbrg.getText()+"','"
                +nmbrg1.getText()+"','"
                +hrgbrg2.getText()+"','"
                +tgl+"','"
                +nmksr.getText()+"','"
                +jmlbrg.getText()+"','"
                +total.getText()+"')";
        
        int status = KoneksiDB.execute(SQL);
        if (status == 1 ){
        JOptionPane.showMessageDialog(this, "Data Berhasil di tambahkan","Sukses",JOptionPane.INFORMATION_MESSAGE);
        }
        else {
        JOptionPane.showMessageDialog(this, "Data gagal ditambahkan","Sukses", JOptionPane.WARNING_MESSAGE);
        }
        

        // TODO add your handling code here:
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btndiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndiskonActionPerformed
int harga = Integer.parseInt(hrgbrg2.getText().toString());
        if (harga >= 100000){
      
            int diskon = harga*30/100;
            txtdiskon.setText(""+diskon);
}else {
        txtdiskon.setText(""+0);
        }



        // TODO add your handling code here:
    }//GEN-LAST:event_btndiskonActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
   SimpleDateFormat dateFormat = new SimpleDateFormat("yyy-MM-dd");
       String tgl = dateFormat.format(tanggal.getDate());
        int baris = table.getSelectedRow();
        if (baris!= -1){
        String idbarang = table.getValueAt(baris,0).toString();
        String SQL = "DELETE FROM tb_admin WHERE idbarang='"+idbarang+"'";
        int status = KoneksiDB.execute(SQL);
        if(status == 1) {
        JOptionPane.showMessageDialog(this,"Data berhasil dihapus","Sukses", JOptionPane.INFORMATION_MESSAGE);
        
        }
        else {
        JOptionPane.showMessageDialog(this, "Data Gagal di hapus","Gagal",JOptionPane.ERROR_MESSAGE);
        }
        
        } else {
        JOptionPane.showMessageDialog(this,"Pilih Baris terlebih dahulu","Error", JOptionPane.WARNING_MESSAGE);
        }



        // TODO add your handling code here:
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
idbrg.setText(" ");
nmbrg1.setText(" ");
hrgbrg2.setText(" ");
jmlbrg.setText(" ");
nmksr.setText(" ");
total.setText(" ");
txtdiskon.setText(" ");

        // TODO add your handling code here:
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
  
MessageFormat header = new MessageFormat("Transaksi Toko Buku");
MessageFormat footer = new MessageFormat("Page {0,number,integer}    ");
try{
table.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
}catch (java.awt.print.PrinterException e)
{
System.err.format("Cannot print %s%n", e.getMessage());
}        
// TODO add your handling code here:
    }//GEN-LAST:event_btnprintActionPerformed

    private void hrgbrg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrgbrg2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrgbrg2ActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int jumlah = Integer.parseInt(jmlbrg.getText().toString());
int hrg = Integer.parseInt(hrgbrg2.getText().toString());
int hasil = jumlah*hrg;
total.setText(""+hasil);


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frametoko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frametoko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frametoko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frametoko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frametoko().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btndiskon;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton btnsave;
    private javax.swing.JTextField hrgbrg2;
    private javax.swing.JTextField idbrg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jmlbrg;
    private javax.swing.JLabel labeljam;
    private javax.swing.JLabel labeltanggal;
    private javax.swing.JTextField nmbrg1;
    private javax.swing.JTextField nmksr;
    private javax.swing.JButton refresh;
    private javax.swing.JTable table;
    private com.toedter.calendar.JDateChooser tanggal;
    private javax.swing.JTextField total;
    private javax.swing.JTextField txtdiskon;
    // End of variables declaration//GEN-END:variables

    private void setTanggal() {
java.util.Date skrg = new java.util.Date();
java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd/MM/yyyy");
labeltanggal.setText(kal.format(skrg));    
    }

    private void setJam() {
       ActionListener taskPerformer = new ActionListener() {
    
    public void actionPerformed(ActionEvent e) {
    Date dt = new Date();
    int nilai_jam = dt.getHours();
    int nilai_menit = dt.getMinutes();
    int nilai_detik = dt.getSeconds();
    
    if (nilai_jam<=9)
    {
    nol_jam = "0";
    }
    if(nilai_detik<=9)
    {
    nol_detik = "0";
    }
    if (nilai_menit <= 9)
    {
    nol_menit = "0";
    }
    String jam = nol_jam + Integer.toString(nilai_jam);
    String menit = nol_menit + Integer.toString(nilai_menit);
    String detik = nol_detik + Integer.toString(nilai_detik);
    labeljam.setText("Jam " + jam + ":" +menit+":"+detik);
    
    }

};
new Timer(100, taskPerformer).start();  }

    private void selectData() {
               String kolom[] = {"idbarang", "namabarang","hargabarang","tanggal","namakasir","jumlahbarang","totalharga"};
    DefaultTableModel dtm = new DefaultTableModel(null,kolom);
    String SQL = "SELECT * FROM tb_admin";
    ResultSet rs = KoneksiDB.executeQuery(SQL);
    try {
    while (rs.next()){
    String idbarang = rs.getString(1);
    String namabarang = rs.getString(2);
    String hargabarang = rs.getString(3);
    String tanggal = rs.getString(4);
    String namakasir = rs.getString(5);
    String jumlahbarang = rs.getString(6);
    String totalharga = rs.getString(7);
    
    String data[]= {idbarang, namabarang, hargabarang,tanggal, namakasir, jumlahbarang, totalharga};
    dtm.addRow(data);
    }
    }   catch (SQLException ex) {
            java.util.logging.Logger.getLogger(frametoko.class.getName()).log(Level.SEVERE, null, ex);
        }
    table.setModel(dtm);
            }
    }

